language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"

env:
  global:
    - DEPLOYMENT_PERL_VERSION=5.30

before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n Carton
install:
  - 'carton install `test "${TRAVIS_PERL_VERSION}" = "${DEPLOYMENT_PERL_VERSION}" && echo " --deployment"`'
script:
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" carton exec -- prove -lr t
after_success:
  - cover -report coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.net#oklahomer"
    on_success: always
    on_failure: always
